### ISSUE TITLE
Error Report of The Final Submission

### ISSUE THREAD

**Issue by cpsc-helper** [Xinyuan-Ying/CPSC_eie#1]
Error happens when evaluating the predictions.

Traceback (most recent call last):
  File "score_2021.py", line 168, in <module>
    score_avg = score(TESTSET_PATH, RESULT_PATH)
  File "score_2021.py", line 144, in score
    if len(endpoints_pred) == 0:
TypeError: len() of unsized object

**Comment by Xinyuan-Ying** [comment]
Dear sir and Madam:
&nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; We&nbsp;have&nbsp;fixed&nbsp;the&nbsp;error&nbsp;in&nbsp;the&nbsp;code, and&nbsp;the&nbsp;code&nbsp;has&nbsp;been&nbsp;reupdated&nbsp;to&nbsp;GitHub.
&nbsp; &nbsp; We&nbsp;apologize&nbsp;for&nbsp;any inconvenience&nbsp;caused&nbsp;to&nbsp;you&nbsp;before.&nbsp;Please&nbsp;feel&nbsp;free&nbsp;to&nbsp;contact&nbsp;us&nbsp;if&nbsp;you&nbsp;have&nbsp;any&nbsp;questions.


Best wishes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xinyuan-Ying/CPSC_eie"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月7日(星期天) 下午4:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Xinyuan-Ying/CPSC_eie] Error Report of The Final Submission (Issue #1)





 
Error happens when evaluating the predictions.
 
Traceback (most recent call last):
 File "score_2021.py", line 168, in 
 score_avg = score(TESTSET_PATH, RESULT_PATH)
 File "score_2021.py", line 144, in score
 if len(endpoints_pred) == 0:
 TypeError: len() of unsized object
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
